title: Agostino Cesarano
baseURL: /
params:
  description: ''
  layout_style: overflow
  palette: green
  header:
    title: Agostino Cesarano
    tagline: Header Tagline
    profile_img: images/avatar.png
    background: dark
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Chi sono
        url: /about/
        style: link
      - label: Contatti
        url: /contact/
        style: link
    has_social: true
    social_links:
      - label: Instagram
        url: 'https://www.instagram.com/agostino_cesarano/'
        style: icon
        icon_class: fa-instagram
        new_window: true
      - label: GitHub
        url: 'https://github.com/AgostinoCesaranoesarano/'
        style: icon
        icon_class: fa-github
        new_window: true
  footer:
    content: '&copy; Tutti i diritti sono riservati.'
    links:
      - label: ''
        url: 'https://www.stackbit.com'
        style: link
        new_window: true
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
